learning_log/urls.py

from django.urls import path, include
from django.contrib import admin
from learning_log import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    path('категории', views.категории, name='категории'),
    path('открыть_категорию<int:категория_id>', views.открыть_категорию, name='открыть_категорию'),
    path('открыть<int:объявление_id>', views.открыть, name='открыть'),
    path('новое_объявление', views.новое_объявление, name='новое_объявление'),
    
    path("удалить<int:rubric_id>",views.удалить,name="удалить"),
    path("кабинет",views.кабинет,name="кабинет"),
    
    path("поиск",views.поиск,name="поиск"),
    
    path("нет",views.нет,name="нет"),  
]

users/urls.py



from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
# Login page.
path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
path('logout/', views.logout_view, name='logout'),
path('register/', views.register, name='register'),


]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Категория(models.Model):
    категория = models.CharField(max_length=50)
    class Meta:
        verbose_name_plural = 'Категории'
    def __str__(self):
        return self.категория

class Объявление(models.Model):
    категория = models.ForeignKey(Категория,on_delete=models.PROTECT)#нельзя удалить окуда есть записи
    товар = models.CharField(max_length=200)
    фото = models.ImageField(upload_to="photos/%Y/%m/%d/",blank=True)
    описание_товара = models.TextField(max_length=300)
    цена = models.FloatField(blank=True,)#хранит, значение типа Number, которое представляет число с плавающей точкой
    дата = models.DateTimeField(auto_now_add=True)
    wner = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    телефон = models.CharField(max_length=20)
    адрес = models.CharField(max_length=100)
    число = models.IntegerField(null=True)#хранит значение типа Number, которое представляет целочисленное значение
    class Meta:
        verbose_name_plural = 'Объявления'
        ordering = ['-дата']
    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.описание_товара[:50] + "..."
        

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Объявление

class ОбъявлениеForm(forms.ModelForm):
    class Meta:
        model = Объявление
        fields = ("категория", "товар","фото","описание_товара","телефон","адрес", "цена")




learning_logs/views.py
from django.shortcuts import render
from .models import Категория,Объявление
from django.contrib.auth.decorators import login_required #Сначала импортируется функция login_required
# Чтобы перенаправление работало, необходимо внести изменения settings.py (# Мои настройки LOGIN_URL = '/users/login/')
from django.http import Http404
# Create your views here.
цвет = ["#FFD700","#0000FF","#32CD32"]

def index(request):
    категории = Категория.objects.all()
    объявлении = Объявление.objects.all()
    context = {"категории":категории,"объявлении":объявлении,"цвет":цвет}
    return render(request, 'learning_logs/index.html',context)

def категории(request):
    категории = Категория.objects.all()
    context = {"категории":категории,"цвет":цвет}
    return render(request, 'learning_logs/категории.html',context)

def открыть_категорию(request,категория_id):
    bbs = Объявление.objects.filter(категория=категория_id)
    объявлении = Объявление.objects.all()
    категории = Категория.objects.all()
    context = {"bbs":bbs,"категории":категории,"объявлении":объявлении,"цвет":цвет}
    return render(request, 'learning_logs/открыть_категорию.html',context)

def открыть(request,объявление_id):
    bbs = Объявление.objects.get(id=объявление_id)
    ййй = bbs.число
    if ййй == None:
        ййй = 0
    ййй += 1
    bbs.число = ййй
    bbs.save()
    context = {"bbs":bbs,}
    return render(request, 'learning_logs/открыть.html',context)


from django.http import HttpResponseRedirect#класс HttpResponseRedirect, который будет использоваться для перенаправления пользователя к странице topics
from django.urls import reverse#Функция reverse() определяет URL по заданной схеме URL
from .forms import ОбъявлениеForm#импортируется только что написанная форма TopicForm
@login_required
def новое_объявление(request):#запрос
    qqq = Объявление.objects.filter(wner=request.user)
    число = len(qqq)
    if число >= 3:
        return HttpResponseRedirect(reverse('learning_logs:кабинет'))
    """Определяет новую тему."""
    if request.method != 'POST':#GET для чтения с сервера.POST для заполнения и отправки через форму
        # Данные не отправлялись; создается пустая форма.
        form = ОбъявлениеForm()#Если метод запроса отличен от POST вернуть пустую форму
    else:
        # Отправлены данные POST; обработать данные.
        form = ОбъявлениеForm(request.POST, request.FILES)# передаем ему данные, введенные пользователем, хранящиеся в request.POST
        if form.is_valid():
            new_topic = form.save(commit=False)#Чтоб небыла нуль
            new_topic.wner = request.user#Важно ---- wner
            if new_topic.цена == None:
                new_topic.цена = 0
            new_topic.save()                      
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:index'))#После того как данные будут сохранены, страницу можно покинуть (см.книгу)
    context = {'form': form}
    return render(request, 'learning_logs/новое_объявление.html', context)

@login_required
def кабинет(request):
    bbs = Объявление.objects.filter(wner=request.user)
    число = len(bbs)
    context ={"bbs": bbs,"число":число}
    return render(request, "learning_logs/кабинет.html ", context)

@login_required
def удалить(request, rubric_id):
    удалить = Объявление.objects.get(pk=rubric_id)
    удалить.delete()
    return HttpResponseRedirect(reverse('learning_logs:кабинет'))


def поиск (request):
    категории = Категория.objects.all()
    объявлении = Объявление.objects.all()
    person = request.POST.get("имя")
    bbs = Объявление.objects.filter(товар=person)
    if len(bbs)!= 0:      
        context = {"person": person,"bbs": bbs,"категории":категории,"объявлении":объявлении,"цвет":цвет}
        return render(request, "learning_logs/поиск.html ", context) 
    else:
        return HttpResponseRedirect(reverse('learning_logs:нет'))
        
def нет (request):
    return render(request, "learning_logs/нет.html ")









users/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout

# Create your views here.
def logout_view(request):
    """Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
  
def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
          
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
        return redirect('learning_logs:index')
  
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="/media/static/main.css">
</head>
<body>
	
<div class="ссылки">	
	<a href="{% url 'learning_logs:index' %}"><button>Главная страница</button></a>
	<a href="{% url 'learning_logs:категории' %}"><button>Категории</button></a>
	<a href="{% url 'learning_logs:новое_объявление' %}"><button>Добавить объявление</button></a>

	{% if user.is_authenticated %}
	    	Hello, {{ user.username }}.
	<a href="{% url 'users:logout' %}"><button>log out</button></a>
 		{% else %}
	<a href="{% url 'users:register' %}"><button>register</button></a>
	   	<a href="{% url 'users:login' %}"><button>log in</button></a>
 		{% endif %}
	<a href="{% url 'learning_logs:кабинет' %}"><button>кабинет</button> </a>

<form method="POST" action="поиск" >
        {% csrf_token %}
        <p>
            
            <input type="text" name="имя" />
	    <input type="submit" value="Поиск" >
        </p>  
</form >
</div>

<div class="block">
{% block content %}{% endblock content %}
</div>


</body>
</html>


learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}


{% for й in объявлении %}

<div  class="запись">
	
	<div class="фото">
	{% if й.фото %}
 		<img src="{{й.фото.url}}" width="250" height="250">
	{% endif %}
	</div>
	
	<div class="текст">
	{% if й.категория.pk == 1 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.0}}>{{й.категория}}</font></a>
		{% elif й.категория.pk == 2 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.1}}>{{й.категория}}</font></a>
		{% elif й.категория.pk == 3 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.2}}>{{й.категория}}</font></a>
	{% endif %}
	<center><h2 class="qq">{{ й.товар }}</h2></center>
	<center>{{ й.описание_товара|linebreaks|truncatewords:15 }}</center>
	<h3>Цена: {{ й.цена }}</h3>
	Дата: {{ й.дата }}
	<center><a href="{% url 'learning_logs:открыть' й.pk %}"> <button class="кнопка_от">Открыть</button> </a></center>

	</div>
	
</div>
{% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/кабинет.html
{% extends "learning_logs/base.html" %}
{% block content %}
<center>
	<h1> Привет</font> :{{ user.username }} </h1>
 	<h4>На данный момен у вас <font color="#32CD32" size="7">{{ число }}</font> объявления</h4>
	( Максимальное число объявлени <font color="#ff0000">3</font> )
</center>
	<br><br>
	<div class="w">
{% for й in bbs %}

 	<div class="привет">
	<center><p><h1>{{ й.товар }}</h1></p></center>
	<p>{{ й.дата }}</p>
    <center>  
    {% if й.фото %}
              <p><img  src="{{й.фото.url}}" width="200" height="200"></p>
	{% endif %}
	</center>
	<h1>Цена : {{ й.цена }} </h1>
	<center><h3>Оисание товара</h3>	</center>
	<p>{{ й.описание_товара|linebreaks}}</p>
    
	<center><a href="{% url 'learning_logs:удалить' й.pk %}"> <button class="кнопка_уд">удалить</button> </a></center>
	</div>
<br>

{% endfor %}
</div>
{% endblock content %}

learning_logs/templates/learning_logs/категории.html
{% extends "learning_logs/base.html" %}

{% block content %}

<center><h1>Категории</h1>

<ol>
	{% for й in категории %}
	<div class="категории">
<li>
{% if й.pk == 1 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.pk %}" class="q"><font color={{цвет.0}}>{{й}}</font></a>
		{% elif й.pk == 2 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.pk %}" class="q"><font color={{цвет.1}}>{{й}}</font></a>
		{% elif й.pk == 3 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.pk %}" class="q"><font color={{цвет.2}}>{{й}}</font></a>
	{% endif %}
</li>
	</div>
  	{% empty %}
		Категори отсутствуют
	{% endfor %}
</ol>
</center>

{% endblock content %}

learning_logs/templates/learning_logs/нет.html

<center>
<h1>Поиск по вашему запросу не дал результата</h1>
<a href="{% url 'learning_logs:index' %}"><button>Главная страница</button></a>
</center>

learning_logs/templates/learning_logs/новое_объявление.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Добавить новое объявление</p>
	  <form action="{% url 'learning_logs:новое_объявление' %}" method='post' enctype="multipart/form-data"> <! Аргумент action сообщает серверу, куда передавать данные, отправленные формай >
	    {% csrf_token %}                                                <!для предотвращения попыток получения несанкционированного доступа к серверу >
	    {{ form.as_p }}                                                 <!отображается форма >
	    <button name="submit">Добавить объявление</button>                        <!Django не создает кнопку отправки данных для форм, поэтому мы определяем ее >
  </form>
    
{% endblock content %}  

learning_logs/templates/learning_logs/открыть.html
{% extends "learning_logs/base.html" %}
{% block content %}


<div class="открыть">
</center> 
    
	{% if bbs.цена == 0 %}
  		<h3>Цена : <font color="#32CD32">Беслатно</font> </h3>
	{% endif %}
	{% if bbs.цена != 0 %}
        	<h3> Цена : {{ bbs.цена }}</h3>
	{% endif %}



	<h3>Имя :{{bbs.wner  }}</h3>
	<h3><span style='font-size:50px;'>&#9742;</span>   Телефон :{{bbs.телефон}}</h3>

	{% if bbs.адрес == None %}
  		<h3>Адрес:<font color="#32CD32">Отсутствует</font> </h3>
	{% else %}
        <h3>Адрес :{{bbs.адрес}}</h3>
<h3>Просмотры :{{bbs.число}}</h3>

	{% endif %}

       <center>  

 
<style>
   .leftimg {
    float:left; /* Выравнивание по левому краю */
    padding: 15px; /* Поля вокруг текста */
   }
</style>
<hr>
	{% if bbs.фото %}
              <img  src="{{bbs.фото.url}}" width="250" height="250" class="leftimg">
	{% endif %}
<center>
<h1><p>{{ bbs.товар }}</p></h1>
<p>{{ bbs.дата }}</p>
<hr>
<h4>Описание товара</h4>
</center>
<p>{{ bbs.описание_товара|linebreaks}}</p>
<hr>
<center>

	

</center>        
<br>	
<center>  
<a href="#" onclick="history.back();return false;"><button class="кнопка_за">Закрыть</button></a>
</center>
<br>

</div>
{% endblock content %}



learning_logs/templates/learning_logs/открыть_категорию.html
{% extends "learning_logs/base.html" %}

{% block content %}

{% for й in bbs %}
<div class="запись">
	<div class="фото">
{% if й.фото %}
	<img  src="{{й.фото.url}}" width="250" height="250" >
{% endif %}
	</div>
	<div class="текст">
	{% if й.категория.pk == 1 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.0}}>{{й.категория}}</font></a>
		{% elif й.категория.pk == 2 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.1}}>{{й.категория}}</font></a>
		{% elif й.категория.pk == 3 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.2}}>{{й.категория}}</font></a>
	{% endif %}
<center><h2>{{ й.товар }}</h2></center>
<center>{{ й.описание_товара|linebreaks|truncatewords:15 }}</center>
<h3>Цена : {{ й.цена }} </h3>
Дата:{{ й.дата }}
	
<center><a href="{% url 'learning_logs:открыть' й.pk %}"><button>Открыть</button> </a></center>
	</div>	
</div>
{% endfor %}
    
{% endblock content %}

learning_logs/templates/learning_logs/поиск.html
{% extends "learning_logs/base.html" %}

{{person}}

{% block content %}

{% for й in bbs %}

<div  class="запись">	
	<div class="фото">
	{% if й.фото %}
 		<img src="{{й.фото.url}}" width="250" height="250">
	{% endif %}
	</div>
	
	<div class="текст">
	{% if й.категория.pk == 1 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.0}}>{{й.категория}}</font></a>
		{% elif й.категория.pk == 2 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.1}}>{{й.категория}}</font></a>
		{% elif й.категория.pk == 3 %}
		<a href="{% url 'learning_logs:открыть_категорию' й.категория.pk %}" ><font color={{цвет.2}}>{{й.категория}}</font></a>
	{% endif %}
	<center><h2 class="qq">{{ й.товар }}</h2></center>
	<center>{{ й.описание_товара|linebreaks|truncatewords:15 }}</center>
	<h3>Цена: {{ й.цена }}</h3>
	Дата: {{ й.дата }}
	<center><a href="{% url 'learning_logs:открыть' й.pk %}"> <button class="кнопка_от">Открыть</button> </a></center>
	</div>	
</div>
{% endfor %}


{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}                           <!шаблон в одном приложении может расширять шаблон из другого приложения.>
{% block content %}

{% if form.errors %}
<p> ошибка (комбинация пороля и имени неверноя)  </p>           <!form.errors (выводится сообщение об ошибке)>

{% endif %}
    
	  <form method="post" action="{% url 'users:login' %}">   <!Мы хотим, чтобы представление обработало форму, поэтому аргументу action присваивается URL страницы входа>
  {% csrf_token %}
	  {{ form.as_p }}                                         <!вывести форму>
    
	  <button name="submit">log in</button>              
	  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" /> <!включается скрытый элемент формы 'next'; аргумент value сообщает Django, куда перенаправить пользователя после успешно выполненного входа>
  </form>
    
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% block content %}
  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
    
{% endblock content %}